name: Test Hello Action
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: false
        default: 'Hello from manual trigger!'
        type: string

jobs:
  test-hello-action:
    runs-on: ubuntu-latest
    name: Test Hello Action
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Run Hello Action
        uses: sailikhith-stepsecurity/hello-action@a81b1b4a4bb57a918a384a4fddeee191bfc6505c # v1  
        with:
          message: ${{ github.event.inputs.message }}
